package com.incubyte.backend.auth.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

import java.util.Collection;
import java.util.List;

@Entity
@Table(name = "users")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User implements UserDetails {

    /**
     * Primary key generated by PostgreSQL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Email used for login.
     *
     * Must be unique.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Password.
     *
     * Later this will store BCrypt hash.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Role of the user.
     * USER or ADMIN
     */
    @Column(nullable = false)
    private String role;


    /**
     * Returns all roles/authorities assigned to this user.
     *
     * Spring Security checks these authorities while
     * authorizing requests.
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {

        // Convert database role into Spring Security authority.
        return List.of(

                new SimpleGrantedAuthority(

                        "ROLE_" + role

                )

        );

    }

    /**
     * Spring Security uses username for authentication.
     *
     * In our application, email acts as the username.
     */
    @Override
    public String getUsername() {
        return email;
    }

    /**
     * Returns encrypted password.
     */
    @Override
    public String getPassword() {
        return password;
    }

    /**
     * Indicates whether the account has expired.
     *
     * Returning true means account is active.
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * Indicates whether the account is locked.
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * Indicates whether credentials have expired.
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * Indicates whether this user is enabled.
     */
    @Override
    public boolean isEnabled() {
        return true;
    }
}