package com.incubyte.backend.auth.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "users")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Primary key generated by PostgreSQL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Email used for login.
     *
     * Must be unique.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Password.
     *
     * Later this will store BCrypt hash.
     */
    @Column(nullable = false)
    private String password;

}